{
  'targets': [
    {
      'target_name': 'nanoleaf',
      # import all necessary source files
      'sources': [
        'dist/nanoleaf.h', # this file was generated by go build
        'nanoleaf.cc'
      ],
      # libraries are relative to the 'build' directory
      'libraries': [ '../dist/nanoleaf.a' ] # this file was also generated by go build
    }
  ]
}
