package types

const (
	PANEL_AURORA = 0
	PANEL_CANVAS = 2
)
const (
	NANOLEAF_AURORA = "NL22"
	NANOLEAF_CANVAS = "NL29"
	NANOLEAF_SHAPES = "NL42"
	// NANOLEAF_ = "NL52"
	// NANOLEAF_ = "NL59"
	// NANOLEAF_ = "NL64"
	// NANOLEAF_ = "NL69"
)

const (
	SHAPETYPE_TRIANGLE              = 0
	SHAPETYPE_RHYTM                 = 1
	SHAPETYPE_SQUARE                = 2
	SHAPETYPE_CONTROL_SQUARE_MASTER = 3
	SHAPETYPE_CONTROL_SQUARE_PASSIV = 4
	SHAPETYPE_HEXAGON_SHAPE         = 7
	SHAPETYPE_TRIANGLE_SHAPE        = 8
	SHAPETYPE_TRIANGLE_MINI_SHAPE   = 9
	SHAPETYPE_CONTROL_SHAPE         = 12
)
